### PR TITLE
Upgrade gems and some fixes

### PR DESCRIPTION
**Pull request by fernandoluizao**
Hi,

I'm starting to using your fork, thanks a lot for the effot of maintaing it!

I have updated rails and some other gems. I'm also using ruby 2.5, it works perfectly.

There are some errors running tests though... not sure how to solve yet...

```
Failed examples:

rspec ./spec/models/issue_trackers/bitbucket_issues_tracker_spec.rb:4 # IssueTrackers::BitbucketIssuesTracker should create an issue on BitBucket Issues with problem params, and set issue link for problem
rspec ./spec/models/issue_trackers/github_issues_tracker_spec.rb:4 # IssueTrackers::GithubIssuesTracker should create an issue on GitHub Issues with problem params, and set issue link for problem
rspec ./spec/models/issue_trackers/mingle_tracker_spec.rb:4 # IssueTrackers::MingleTracker should create an issue on Mingle with problem params, and set issue link for problem
rspec ./spec/models/issue_trackers/redmine_tracker_spec.rb:4 # IssueTrackers::RedmineTracker should create an issue on Redmine with problem params, and set issue link for problem
rspec ./spec/models/issue_trackers/unfuddle_issues_tracker_spec.rb:10 # IssueTrackers::UnfuddleTracker should create an issue on Unfuddle Issues with problem params, and set issue link for problem
rspec ./spec/models/notification_service/flowdock_service_spec.rb:8 # NotificationServices::FlowdockService sends message in appropriate format
```

### CODE REVIEW

**Comment by boblail** [comment]
Thanks for your work on this, @fernandoluizao!

I tried retracing your steps and upgrading gems more slowly, with `bundle update --conservative`, to isolate which gems _have_ to be upgraded to get Errbit running on Ruby 2.5. (See #15)

It looks like `oj`, `therubyracer`, and `devise` all have to be upgraded — and that upgrading these three is pretty painless.

This leaves two failing specs in `pivotal_labs_tracker_spec.rb`. These specs fail with an exception because our version of `webmock` (1.15.0) isn't compatible with Ruby 2.4+.

Upgrading to the latest 1.x version of webmock doesn't help; but upgrading to either 2.3.2 (`~> 2.0`) or 3.4.2 (`~> 3.0`) resolves both exceptions while introducing API changes that break 5 other specs.

I'm open to a couple of paths:

 1. Dropping `app/models/issue_trackers/pivotal_labs_tracker.rb` (It's implemented based on the `pivotal-tracker` gem, which hasn't seen a release in 3 years.)
 2. Updating webmock and fixing those specs according to Webmock's breaking [API changes](https://github.com/bblimke/webmock/blob/master/CHANGELOG.md)

**Comment by fernandoluizao** [comment]
@boblail I'm working to make tests pass. I'm also trying to fix lots of warnings when running tests.

Hopefully tomorrow I wil have everything working.

**Comment by fernandoluizao** [comment]
Tests are green :smile: 

There are some warnings... related to deprecated [should](https://github.com/rspec/rspec-expectations/blob/master/Should.md) matchers, and email_spec. I couldn't upgrade email_spec to fix the warning, since one test fails...

**Comment by boblail** [comment]
Awesome! Thanks, @fernandoluizao!

**Pull request merged**
